Bookstore: initialize project with components
Yazino12/bookstore pull request #1
Opened 2022-04-29 07:20 UTC by Yazino12

### In this pull:

- Initialize the project with components
- Add components: BookStore, BookList, Book, Navbar, AddBook
- Add pages: Categories
- Install dependencies: react-router-dom, UUID
- Use React hooks: state, setState
- Use React props and state lifting
- Add basic styling
- Update readme

2022-04-29 07:39 UTC, Deepakdanger requested changes
Hi @Yazino12, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight :100: 
- Good PR :heavy_check_mark: 

## Required Changes ♻️
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-29 07:39 UTC, Deepakdanger commented on src/components/AddBook.js
> +/* eslint-disable react/prop-types */
- [ ] Kindly enable this ESlint and add prop-types to fix that linter issue. Please refer [this](https://reactjs.org/docs/typechecking-with-proptypes.html) for understanding prop-type.

2022-04-29 07:39 UTC, Deepakdanger commented on src/components/Book.js
> +/* eslint-disable react/prop-types */
- [ ] Kindly enable this ESlint and add prop-types to fix that linter issue. Please refer [this](https://reactjs.org/docs/typechecking-with-proptypes.html) for understanding prop-type.

2022-04-29 07:39 UTC, Deepakdanger commented on src/components/BookList.js
> +/* eslint-disable react/prop-types */
- [ ] Kindly enable this ESlint and add prop-types to fix that linter issue. Please refer [this](https://reactjs.org/docs/typechecking-with-proptypes.html) for understanding prop-type.

2022-04-29 07:39 UTC, Deepakdanger commented on src/components/BookStore.js
> +/* eslint-disable react/prop-types */
- [ ] Kindly enable this ESlint and add prop-types to fix that linter issue. Please refer [this](https://reactjs.org/docs/typechecking-with-proptypes.html) for understanding prop-type.

2022-04-29 10:01 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾✔🎉**
Hello @Yazino12 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Github inline comments feature is used properly.
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-29 10:04 UTC, merged

2022-06-02 10:41 UTC, Yazino12 commented on src/components/BookStore.js
> +/* eslint-disable react/prop-types */
Thanks, @Deepakdanger for the guidance, I will apply these changes right away 😊.

2022-06-02 10:41 UTC, Yazino12 commented on src/components/BookList.js
> +/* eslint-disable react/prop-types */
Thanks, @Deepakdanger for the guidance, I will apply these changes right away 😊.

2022-06-02 10:41 UTC, Yazino12 commented on src/components/Book.js
> +/* eslint-disable react/prop-types */
Thanks, @Deepakdanger for the guidance, I will apply these changes right away 😊.

2022-06-02 10:41 UTC, Yazino12 commented on src/components/AddBook.js
> +/* eslint-disable react/prop-types */
Thanks, @Deepakdanger for the guidance, I will apply these changes right away 😊.